version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "main"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
